kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  serviceSubnet: "10.112.0.0/16"  # Avoids overlap with docker-desktop (10.96.0.0/12)
  podSubnet: "10.114.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.32.5
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        protocol: TCP
