apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: twotier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: "{{ .Values.image.repository }}/auth-service:{{ .Values.image.auth_tag }}"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: auth-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-credentials
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: auth-credentials
              key: DB_PASS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-credentials
              key: JWT_SECRET
        ports:
        - containerPort: 3000
