apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: twotier
type: Opaque
stringData:
  FEATURE_FLAG: "featureflag"
  JWT_SECRET: "mh9k3Y8+JqD7rCnf0XeyU4tQz5VhmAd0YlBp7Km5Z2s="
