apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-service
  namespace: twotier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tx-service
  template:
    metadata:
      labels:
        app: tx-service
    spec:
      containers:
      - name: tx
        image: "{{ .Values.image.repository }}/tx-service:{{ .Values.image.tx_tag }}"
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-credentials
              key: JWT_SECRET
        ports:
        - containerPort: 4000
