apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
type: Opaque
data:
  DB_HOST: dHdvVGl...        # base64 of twoTierPgServer.postgres.database.azure.com
  DB_USER: ZGJhZG1pbkB0d29UaWVyUGdTZXJ2ZXI=  # dbadmin@twoTierPgServer
  DB_PASS: WW91clBAc3N3MHJkIQ==              # YourP@ssw0rd!
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: c2VjcmV0MTIz      # base64 of secret123
