kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  serviceSubnet: "10.97.0.0/16"  # Avoids overlap with docker-desktop (10.96.0.0/12)
  podSubnet: "10.98.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.32.2
  extraPortMappings:
    - containerPort: 30080  # Maps NodePort to host for ingress
      hostPort: 30080
      protocol: TCP
- role: worker
  image: kindest/node:v1.32.2
- role: worker
  image: kindest/node:v1.32.2
