apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"      # ~0.1 core
            memory: "128Mi"  # 128 MB
          limits:
            cpu: "250m"      # ~0.25 core
            memory: "256Mi"  # 256 MB
